### ISSUE TITLE
Thoughts about Cloudflare?

### ISSUE THREAD

**Issue by AbhiAgarwal** [TechAtNYU/tech-nyu-site#38]
Hey.

Any thoughts about using Cloudflare for the site? It'll help with caching and also our HTTPS issue.

I think it's a great idea. I've used it for all my projects, and it's a little overkill, but it always helps in speed (for me atleast)

**Comment by ethanresnick** [comment]
cc @thebyrd. This issue seems to imply that we moved to cloudflare a while ago, but I guess not. Is the move totally done now? If so, I'll close this.

**Comment by thebyrd** [comment]
@ethanresnick it's done. Previously you were using namecheap's DNS

**Comment by ethanresnick** [comment]
two more things about this, prompted by @thebyrd's [comment](https://github.com/TechAtNYU/tech-nyu-site/issues/57#issuecomment-76794092) about cloudflare caching

1. going forward, is there any way we can automatically ping cloudflare when we redeploy, to get it to invalidate its cache? 
2. how is this going to affect the event on the homepage updating? can we control the cloudflare ttl?

**Comment by ethanresnick** [comment]
nvm, going to open a new issue
