### ISSUE TITLE
Events no longer updating

### ISSUE THREAD

**Issue by ethanresnick** [TechAtNYU/tech-nyu-site#49]
Hey guys,

Any idea why the "Upcoming Event" panel on the homepage is no longer updating? (It's been stuck on Studio Time for a few days.) Was the site deployed as a static page for some reason, rather than a node app? Idk. The event seems to update on my local system

**Comment by AbhiAgarwal** [comment]
@ethanresnick sites back up! I don't have my computer right now so I can't do anything else (for now)

**Comment by AbhiAgarwal** [comment]
It's been fixed! I pulled and restarted after @ethanresnick's fix.

**Comment by ethanresnick** [comment]
@AbhiAgarwal This still isn't working. I just tried it today and the new event isn't showing up. All my fix did was update the code to use the new payload structure but, even before the payload structure changed (i.e. when the site's parsing code was right), this wasn't working. So something else is going on.

**Comment by ethanresnick** [comment]
Nvm, just fixed it.
