### ISSUE TITLE
Githook for deployment

### ISSUE THREAD

**Issue by ethanresnick** [TechAtNYU/tech-nyu-site#59]
Should auto redeploy the site when a commit is made, including:

1. rebuilding the livescript, sass, etc.
2. invalidate all the cloudflare caches, with the code David sent over slack

**Comment by ethanresnick** [comment]
@AbhiAgarwal Setting up this (or at least manually redeploying the site) is extra important right now, since we want to start marketing our Edward Tufte event, which requires the techatnyu.org redirect that I [just added](https://github.com/TechAtNYU/tech-nyu-site/commit/1ddc9aa6ee135f22ec5d437186f754d7ed6e0691). If you could handle this asap, I'd really appreciate it!

**Comment by AbhiAgarwal** [comment]
I manually pulled it. I won't be able to do much until after spring break now - sorry.

**Comment by ethanresnick** [comment]
This is done now by circleci.
