### ISSUE TITLE
All next-event goes to nyusw.com

### ISSUE THREAD

**Issue by AbhiAgarwal** [TechAtNYU/tech-nyu-site#60]
Disable it after SW ends

**Comment by irisyuan** [comment]
Is this disabled? The next event still links to nyusw instead of the next design event

**Comment by AbhiAgarwal** [comment]
@ethanresnick 

This is the translation into Javascript.

```
updateData = function(){
  var ref$;
  if ((ref$ = data.promo) != null && ref$.isEvent) {
    Q.nfcall(request, {
      url: 'https://api.tnyu.org/v1.0/events/up-next-publicly',
      rejectUnauthorized: false,
      method: "GET"
    }).then(function(arg$){
      var response, body, nextEvent;
      response = arg$[0], body = arg$[1];
      if (response.statusCode === 200 && body) {
        nextEvent = JSON.parse(body).events;
        if (nextEvent) {
          return data.promo = {
            shortTitle: nextEvent.shortTitle,
            shortDescription: nextEvent.description,
            moreInfoUrl: nextEvent.rsvpUrl,
            isEvent: true
          };
        }
      }
    });
  setTimeout(updateData, 3600000);
  };
}
updateData();
```

What is ` if ((ref$ = data.promo) != null && ref$.isEvent) {` supposed to do? I did a `console.log` and `data.promo` is not in data.

**Comment by AbhiAgarwal** [comment]
Just an FYI I removed that line and it works. I'm not too sure how `data` plays into this particular function. I get that if we were to add a promo we would add that into `data` (that's defined directly above that function). But this shouldn't be an `if` statement around the whole block.

**Comment by ethanresnick** [comment]
@AbhiAgarwal the fix you applied works for now. The only thing it doesn't do is support our falling back to a default promo message when there is no next event. That's what the old code was trying to do, but it had a bug, which is why it wasn't working.

Let's stick with your fix for now, since it gives us all we need until the end of the year. But I'm leaving this issue open as a reminder to myself to add the fallback logic after finals

**Comment by grungerabbit** [comment]
did we ever fix this? bahaha

**Comment by AbhiAgarwal** [comment]
@grungerabbit I think the solution right now works. The current event doesn't have an RSVP url so it doesn't appear.

**Comment by grungerabbit** [comment]
great, closing. :fire:
